#
# @file
#   Pre-Commit configuration YAML file.
#
# @copyright
#   Copyright (c) 2022 Jason Lin <jason40418@gmail.com>.
#   SPDX-License-Identifier: BSD-2-Clause
#
# @par reference
#    - pre-commit: https://pre-commit.com/
#
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
